### ISSUE TITLE
User is logged out after a few hour in hybrid app

### ISSUE THREAD

**Issue by wojtekk** [schibsted/sdk-ios#24]
Hi, I think I found issue in `SPiDHybridApp` - we use this library in BT app: https://itunes.apple.com/pl/app/bt.no/id435546727?mt=8

Issue: User is logged out after a few hour.

How reproduce this error:
1. Install app
2. Login
3. Read something
4 ... long break f.ex. whole night
5. run app 
6. read closed article

When I try do that I see salesposter.

I think, issue exists because `webview` lost cookie: `SP_ID` important for Varnish. App/library should recreate it. This cookie exists only for a few hours.

**Comment by mikaoj** [comment]
Hi! This sdk doesn't have a real maintainer and I'm probably the closest to being one at the moment. So I'll ask som basic questions to get those squared away:

Which version of the sdk are you using?
Does this occur on any specific versions of iOS or devices?
Is the bug reproducible in the SPiDHybridApp example in this repo?

**Comment by wojtekk** [comment]
Hi, we use newest version. 

I can't reproduce the error in example app because app uses static HTML.

I think key point is that SPiD Varnish module uses cookie `SP_ID` to works properly. I don't see it in repository so SDK does not set it :/

**Comment by danielbentes** [comment]
The SDK does not set the varnish cookie. The cookie is set by SPiD through the webview itself via the Javascript SDK running on it. The cookie timeout is specified in the initialisation of the javascript sdk.

The way I see it this is solvable in many ways:
1) Extend the varnish cookie timeout for webviews in the javascript initialisation
2) Re-initiate the authentication (and following cookie refresh) after a certain period in the app itself. The user's session in the webview lasts for 2 hours of inactivity. So if the user opens the app after 2 hours you know the user wont be logged in. The varnish cookie can have a longer timeout, but  since the app knows the user isn't logged in anymore a refresh of the session is probably what you need.
3) Implement the APi for retrieving and setting the varnish cookie in the webview (http://techdocs.spid.no/endpoints/GET/user/{userId}/varnishId/)

**Comment by wojtekk** [comment]
That makes sense - thanks for your help and explanations.
